### ISSUE TITLE
Пустые графики rrd

### ISSUE THREAD

**Issue by jeka57** [gSpotx2f/smarthtml#1]
Доброго дня! Все данные показываются, но никак не могу заставить скрипт рисовать графики. Они есть на странице, но пустые. Такое ощущение, что скрипт не может записать данные в базу данных rrd, но никаких сообщений или ошибок в логах нет.

**Comment by anch665** [comment]
У меня тоже не рисует графики температуры и время раскручивания винта.
А так же не выполняется задание из крона, хотя если заупстит вручную то все работает
