### ISSUE TITLE
В разделе Mounted filesystems отображает лишний символ /n

### ISSUE THREAD

**Issue by anch665** [gSpotx2f/smarthtml#2]
было так:
  echo "</tbody></table> \n</section>" >> $HTML_OUTPUT
исправил так:
  echo "</tbody></table></section>" >> $HTML_OUTPUT

Это опечатка или для чего-то конкретного?

**Comment by gSpotx2f** [comment]
Можно ссылку на строку в [листинге](https://github.com/gSpotx2f/smarthtml/blob/master/usr/bin/smarthtml) файла? Я не нашёл такой строки `echo " \n" >> $HTML_OUTPUT`... Есть [строка](https://github.com/gSpotx2f/smarthtml/blob/cbabf8447c68764a6325a4adac53352ce9633084/usr/bin/smarthtml#L599) `echo "</tbody></table> \n</section>" >> $HTML_OUTPUT`. В последнем коммите добавил переносы строк для более удобного форматирования финального HTML-кода (чтобы в браузере в исходном коде было проще ориентироваться).

**Comment by anch665** [comment]
У тебя в коде это строка 599
 echo "</tbody></table> \n</section>" >> $HTML_OUTPUT

Я понял что это перенос, но он ее отображает как /n

**Comment by anch665** [comment]
[если не исправить, то выглядит так](https://drive.google.com/file/d/10Eab5fJEKTN5oTfn8p1OFl7i5OIYwO5D/view?usp=sharing)

**Comment by gSpotx2f** [comment]
echo не распознаёт escape-последовательности без ключа `-e`. [Заменил на printf](https://github.com/gSpotx2f/smarthtml/commit/74c096b51c65cfad51408eb2c50b690058b74387)...

**Comment by anch665** [comment]
теперь все отлично!
