### ISSUE TITLE
Уведомление в telegram

### ISSUE THREAD

**Issue by anch665** [gSpotx2f/smarthtml#3]
Если не сложно, хотелось бы сделать уведомление о изменении параметров смарт в Телеграм вместо почты

**Comment by gSpotx2f** [comment]
[Вот](https://gist.github.com/gSpotx2f/09c2c9b7bc354f8bb6c4d4c97551358a) скрипт на основе скрипта из [Padavan's wiki](https://bitbucket.org/padavan/rt-n56u/wiki/RU/%D0%9E%D1%82%D0%BF%D1%80%D0%B0%D0%B2%D0%BA%D0%B0%20%D1%81%D0%BE%D0%BE%D0%B1%D1%89%D0%B5%D0%BD%D0%B8%D0%B9%20%D0%B2%20Telegram). Не ручаюсь за его работоспособность, я не пользуюсь telegram и поэтому не могу протестировать.
Скачайте скрипт в `/opt/usr/bin/smarthtml_mailer_tg`, разрешите выполнение: `chmod +x /opt/usr/bin/smarthtml_mailer_tg`. В конфиге /opt/etc/smarthtml.conf: `MAILER_SCRIPT="/opt/usr/bin/smarthtml_mailer_tg"` и `USE_MAIL=1`. Далее выпоните все шаги из инструкции Padavan'а по созданию бота в tg, заполнению `API_TOKEN` и `CHAT_ID` в smarthtml_mailer_tg. Потом тестируйте: `smarthtml mailtest`. Если, вдруг, всё заработает, то отпишитесь здесь и я добавлю скрипт в проект и описание в wiki.

**Comment by anch665** [comment]
Переделал smarthtml_mailer_tg с wget на curl, так он хотя бы отправляет сказанный файл в телегу, 
к сожалению при выполнении smarthtml mailtest  ни чего не происходит, я правильно понимаю что в каталоге /opt/var/smarthtml/message должен появится файл сообщения, в общем его там нет
```
MTA_MSG_FILE="$1"
DEBUG="$2"
CURL_CMD=`which curl`
if [ $? -ne 0 ]; then
    echo " Error! curl doesn't exists..." >&2
    exit 1
fi

if [ -z "$CHAT_ID" ]; then
    if [ -n "$DEBUG" ]; then
        echo "Please, define CHAT_ID first! See \"chat\":{\"id\":xxxxxxx string below:"
        $CURL_CMD  -k -i -X GET "https://api.telegram.org/bot${API_TOKEN}/getUpdates"
    fi
    exit 1
fi
MSG="<b>$(nvram get computer_name)</b>: S.M.A.R.T.

<strong>`cat "$MTA_MSG_FILE"`</strong>"

$CURL_CMD --data-urlencode "text=${MSG}" "https://api.telegram.org/bot${API_TOKEN}/sendMessage?chat_id=${CHAT_ID}&parse_mode=html" 2>&1
return_code=$0

if [ -n "$DEBUG" ]; then
    if [ $return_code -eq 0 ]; then
        echo "Message sent successfully."
    else
        echo "Error while sending message!"
        exit 1
    fi
fi
```

**Comment by gSpotx2f** [comment]
Файл с сообщением `/opt/var/smarthtml/message` создаётся во время выполнения smarthtml (если необходимо отправить сообщение) и удаляется сразу после отправки сообщения. Поэтому, вы его не найдёте, он существует несколько секунд пока выполняется программа.

Сам скрипт smarthtml_mailer_tg, ваша версия (с curl вместо wget) работает? Если запускать его как самостоятельный скрипт, без smarthtml?

**Comment by anch665** [comment]
> Да, работает, тестовые сообщения отправляются. curl необходимо установить из entware opkg install curl
этот блок не работает, telegramm сменил API, не разбирался что да как, у меня давно работает бот и я знаю свои чатид и ботид
`        echo "Please, define CHAT_ID first! See \"chat\":{\"id\":xxxxxxx string below:"
        $CURL_CMD  -k -i -X GET "https://api.telegram.org/bot${API_TOKEN}/getUpdates"`


Есть правда один несущественный момент
после выполнения
`/opt/usr/bin/smarthtml mailtest`
сообщение отравляется, но в логах всегда ошибка
`Error while sending message!`
Стало интересно, сделал в коде:
`echo "Error while sending message! $return_code"`
на выходе получил
`Error while sending message! /opt/usr/bin/smarthtml_mailer_tg`

**Comment by gSpotx2f** [comment]
> сообщение отравляется, но в логах всегда ошибка

Опечатка была в скрипте, в строке [39](https://gist.github.com/gSpotx2f/09c2c9b7bc354f8bb6c4d4c97551358a#file-smarthtml_mailer_tg-L39): вместо `$0` должно быть `S?`.

Подытожим: smarthtml_mailer_tg с curl работает, сообщения отправляет. Код для получения CHAT_ID не работает. Надо выяснить как получить CHAT_ID или выпилить из скрипта вообще этот блок? Проверьте пожалуйста [скрипт](https://gist.github.com/gSpotx2f/09c2c9b7bc354f8bb6c4d4c97551358a) из gist, я добавил ваш код с curl...

**Comment by anch665** [comment]
Ваш вариант не работаете, т.к. телега поддерживает ограниченное количество HTML тегов, к сожалению `<br>` в их число не входит.
`{"ok":false,"error_code":400,"description":"Bad Request: can't parse entities: Unsupported start tag \"br\" at byte offset 40"}`
Кстати ответ отдается в таком виде и соответственно блок кода ниже работает не так как надо
`if [ -n "$DEBUG" ]; then
    if [ $return_code -eq 0 ]; then
        echo "Message sent successfully."
    else
        echo "Error while sending message!"
        exit 1
    fi
fi`
return_code всегда возвращает 0

**Comment by anch665** [comment]
оставил такой вариант, и он у меня работает
разобрался с `https://api.telegram.org/bot${API_TOKEN}/getUpdates`, тут все в порядке, отображает как надо

`
export PATH="/opt/bin:/opt/sbin:/opt/usr/bin:/usr/sbin:/usr/bin:/sbin:/bin"
export LANG="en_US.UTF-8"
export LANGUAGE="en"
export HOSTNAME="$HOSTNAME"

MAILER_MSG_FILE="$1"
DEBUG="$2"
CURL_CMD=`which curl`
if [ $? -ne 0 ]; then
    echo " Error! curl doesn't exists..." >&2
    exit 1
fi

if [ -z "$CHAT_ID" ]; then
    if [ -n "$DEBUG" ]; then
        echo "Please, define CHAT_ID first! See \"chat\":{\"id\":xxxxxxx string below:"
        $CURL_CMD -k -i -X GET "https://api.telegram.org/bot${API_TOKEN}/getUpdates"
    fi
    exit 1
fi


MSG="<strong>`cat "$MAILER_MSG_FILE"`</strong>"

$CURL_CMD --data-urlencode "text=${MSG}" "https://api.telegram.org/bot${API_TOKEN}/sendMessage?chat_id=${CHAT_ID}&parse_mode=html"`

**Comment by gSpotx2f** [comment]
Теги [вернул](https://gist.github.com/gSpotx2f/09c2c9b7bc354f8bb6c4d4c97551358a#file-smarthtml_mailer_tg-L36) к начальному варианту, как было в оригинальном скрипте. Посмотрел доки tg, он поддерживает лишь несколько тэгов для выделения текста.

> return_code всегда возвращает 0

$return_code равен 0 если curl работает без ошибок. Ошибки API телеграма находятся внутри успешного результата работы curl :) В общем, $return_code - это проверка правильной работы curl, а не телеграма.

**Comment by anch665** [comment]
Отлично! работает, можно добавлять в вики
